title: "My Tech News"
description: "Новости будущего: нейроинтерфейсы, ИИ, биотехнологии."
keywords: "tech, нейролинки, технологии будущего, новости"

url: "https://YOUR_GITHUB_NAME.github.io"
baseurl: ""

image_dir: "images"

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
